### ISSUE TITLE
Iteration using @ is supported, but @ can't be used in signatures

### ISSUE THREAD

**Issue by Altai-man** [croservices/cro-webapp#20]
Due to https://github.com/croservices/cro-webapp/blob/master/lib/Cro/WebApp/Template/Parser.pm6#L213
```
<:macro page(@categories)>
```
results in
```
Template parse failed: Malformed signature at line 1 near '@categories)>
```
which is not cool.

**Comment by jnthn** [comment]
Only having `$`-sigil things is a deliberate design decision. Actually `<@foo>` is a shortcut for `<@$_.foo>` - only due to an oversight the latter was not actually possible to write until ed51198936. Now it is.
