### ISSUE TITLE
Compilation fails with odd error message (gist inside)

### ISSUE THREAD

**Issue by Altai-man** [croservices/cro-webapp#24]
https://gist.github.com/Altai-man/d3c88ce56e5421e15cbe26567890d3be

The code is broken for sure (see variables, e.g. @categories in layout file), but the error messages do not convey this, instead saying there is some parse error in macro definition.

**Comment by khalidelboray** [comment]
Having the same issue while using @ before a variable to iterate over it eg.                    
```html
<@$post.tags : $tag>
                        <span class="tag"><$tag></span>
</@>
```
 failes with  an odd error ` confused at line 22 near '<:sub post-review($post)>
    <article class'`.  [gist](https://gist.github.com/khalidelboray/520b912b11fe2c4c9a5999bc2e7afbc2)
