### ISSUE TITLE
<@.something> is not supported

### ISSUE THREAD

**Issue by patrickbkr** [croservices/cro-webapp#27]
```
<@.list>
  <.[0]>
  <@.[1]>
    <$_><br/>
  </@>
</@>
```
Is not recognized. The error is:

```
Died with the exception:
    Template parse failed: confused at line 1 near '<@.list>
      <.[0]> 
      <@.[1]>
        <$_><br'
```

The following works fine however:

```
<@list>
  <.[0]>
  <@[1]>
    <$_><br/>
  </@>
</@>
```

It seems as if the `<@.something>` syntax is not recognized, even though `<@something>` is. The documentation states:

> The <@foo> form is short for <@.foo>, and follows the same rules as <.foo> for resolution. It is also possible to write <@$foo> to iterate over a variable.

That suggests the syntax should be supported.

**Comment by jnthn** [comment]
Fixed by #29.
