### ISSUE TITLE
Some warnings are LTA

### ISSUE THREAD

**Issue by lizmat** [croservices/cro-webapp#40]
```
Use of Nil in string context
  in sub escape-attribute at /Users/liz/Github/rakudo.moar/install/share/perl6/site/sources/6A3C744A4C03D3F2184D2210CC3CFBC8E0DBAFDA (Cro::WebApp::Template::AST) line 311
```

doesn't tell me anything about which line in the template, or in the generated code, this actually happened.  Which makes trying to fix this warning really like looking for a needle in the proverbial haystack.

It would be nice if the warning would state that line in the template where it occurred.

**Comment by jnthn** [comment]
Resolved with the merge of #58.
