### ISSUE TITLE
Condition tag doesn't support variable tests as documented

### ISSUE THREAD

**Issue by japhb** [croservices/cro-webapp#5]
`<?$foo>` should work as documented in the README, but it does not; `<?.foo>` and `<?{$foo}>` do work however.  I believe there's just a missing case in the grammar for `'$' <identifier>` in [`token sigil-tag:sym<condition>`](https://github.com/croservices/cro-webapp/blob/master/lib/Cro/WebApp/Template/Parser.pm6#L100) and the [matching code in the actions](https://github.com/croservices/cro-webapp/blob/master/lib/Cro/WebApp/Template/ASTBuilder.pm6#L58).

_(Apologies that this does not come with the obvious PR; I'm on the wrong machine at the moment, and don't want to keep forgetting to report this.)_

**Comment by jnthn** [comment]
Fixed by 6d429f65d4.
