### ISSUE TITLE
None standard http headers are not supported?

### ISSUE THREAD

**Issue by melezhik** [croservices/cro-webapp#55]
Hi! I am trying to add these header to response:

```raku
    given response {
      .append-header('Content-type', 'image/svg+xml');
      .append-header('charset', 'utf-8');
    }
```

but get this error:

```
⚠ sparky Could not parse media type 'image/svg+xml,text/html; charset=utf-8'
⚠ sparky   in method parse at /Users/alex/.rakubrew/versions/moar-/share/perl6/site/sources/33C6742958D3C4ACCFAD0D9DD0C5533ADA26FF0F (Cro::MediaType) line 98
```

HTH

**Comment by raydiak** [comment]
The problem is that the response already has a `text/html` content type and you're appending another, but specifying multiple content types isn't valid. I have no experience with Cro and don't know if this is the correct solution, but you could do `.remove-header('Content-type')` before appending your own.

You might want to leave this issue open for someone more knowledgeable to chime in, there may be a more elegant way to specify it earlier in the pipeline when the response is initially constructed.

**Comment by melezhik** [comment]
`.remove-header('Content-type')` did not help, get the same error. so I ended up using http permanent redirects to static images

**Comment by raydiak** [comment]
Odd, it worked for me in a small test directly using parts of Cro::HTTP. There must be something more going on elsewhere in the execution. Glad you have a workaround for now, though.

**Comment by raydiak** [comment]
I just had a look at your project. You're calling `template`, which sets text/html by default according to the docs. Add `content-type => 'image/svg+xml'` should do the trick. And you can skip all the manual fiddling with headers. Should look something like this:

```raku
template 'templates/badge.crotmp', {
      project => $project, 
      state => $state
    },
    content-type => 'image/svg+xml';
```

See also  https://cro.services/docs/reference/cro-webapp-template and https://github.com/croservices/cro-webapp/blob/3fe83a566efa997ab5d158b75a0576c5e26aee01/lib/Cro/WebApp/Template.pm6#L190-L195

**Comment by melezhik** [comment]
@raydiak  thanks a lot. Honestly I already rewritten the code to use permanent redirect, but I'll consider this solution for the future in case I decide to revert changes and go with template way ... But thanks!

PS cro supporters, should we close this issue or leave it, so someone would update the respected cro templates documentation?

**Comment by raydiak** [comment]
I figured, I just wanted to see it though. Serving static resources through a script is usually better avoided anyway. At least now you know how it works for the future. And you're welcome, of course!

As far as the docs go, they're pretty clear and explicit about this if you look at the one I linked. Is there another document somewhere which gave you the impression that this should work?

The only potential issues I see here are whether `template` should be adding a content type if one is already set, and if multiple content types should be able to be set at all. At the least, perhaps the error could have something like "Is more than one content type specified?" appended after the parse failure message.

**Comment by melezhik** [comment]
template forcefully set a certain content type, without option to override the one via . append-header.  This seems like a bug for me.

**Comment by jnthn** [comment]
The `template` function (like `content`, which it in turn calls) takes a `content-type` option. I just checked if this is documented, and it indeed is. I have, however, tweaked `content` to make sure that it overrides any existing `content-type` header.

**Comment by melezhik** [comment]
cool, thanks
