### ISSUE TITLE
content 'text/plain' silently returns 500 error when gets called with Int argument

### ISSUE THREAD

**Issue by melezhik** [croservices/cro-webapp#56]
Hi! It took me some time to understand that `content` requires  second argument as a `Str` when being called with a first argument as `text-plain`, so:

```raku
content 'text/plain', "1" 
```

works fine, returns 200 OK with `1` as a body

```raku
content 'text/plain', 1 
```

returns 500 error without any stack trace or logs on cro side

**Comment by melezhik** [comment]
@jnthn I assume it is fixed, right?

**Comment by jnthn** [comment]
Yes, the commit that closed it ensures that an error is reported, so it is a silent failure no longer.
