### ISSUE TITLE
How to template a comment

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#63]
An HTML comment has the form `<!-- text -->`

But `<!--` also meets the non-alphabetic rule, so is not treated as content. 

Perhaps `<!--` should be special cased to be considered Content view text?

Also `<!` is used for conditionals. Perhaps 

Currently if I have 'some stuff' in %params, how do I get a comment?
Given a file 'comment.crotmp' with contents
```
<!-- <.contents> -->
```
The following Raku code
```
my %parts;
my %params = ( :contents<this is it> );
dd %params;
say render-template('comment.crotmp', %params, :%parts);
```
Yields 
```
<!-- <.contents> -->
```

I'm trying to get 
```
<!-- this is it -->

**Comment by jnthn** [comment]
You can work around this by `<&HTML('<!--' ~ .contents ~ '-->')>`. The parser does know not to confuse HTML comments with conditionals, and to emit them as comments, however it doesn't attempt to parse that is inside them. We could change that, however I do worry a little if it's been used for avoiding having JavaScript inside of `<script>` tags get considered as part of templating, and we'd thus break that if so.
