### ISSUE TITLE
Handling of non-existent or empty fields

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#64]
A topic object without an attribute needed by a template crashes when another method is available.

Use case: I want to set a `.path` attribute, if it exists, and the `.name` attribute if it does not.
The following template tries to access `.path`.
There is no problem if the topic object has a `path` attribute, but it fails if no `path` is available.
```
<footer>
    <div>Rendered from <span class="path">
    <?.path><.path></?>
    <!.path><.name></!></span></div>
</footer>
```
with 
```
my %params = ( :name<Foo> );
dd %params;
say render-template('footer.crotmp', %params, :%parts);
```
generates
```
<footer>
    <div>Rendered from <span class="path">
    name        foo
    </span></div>
</footer>
Saw 1 occurrence of deprecated code.
================================================================================
Method path (from Cool) seen at:
  EVAL_1, lines 3,4
Please use IO instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
```
But when `path` is replaced by `pathx` we get
```
<footer>
    <div>Rendered from <span class="path">
    
    foo</span></div>
</footer>
```

**Comment by jnthn** [comment]
The `<.foo>` form is specified as hash lookup with method lookup callback, however one can always disambiguate: write `<.<foo>>` for hash lookup only, and `<.foo()>` for method lookup only. Exact details are [in the docs](https://cro.services/docs/reference/cro-webapp-template#Template_language).
