### ISSUE TITLE
Can a variable be set within a template

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#65]
Given a large local topic, would it be possible set a variable to an attribute?
suppose the topic is given to the template such that  
inside the template $_ = ( attr => ( subkey => 'a' ))

<$foo := .attr>
then <$foo.subkey> would render as 'a'

**Comment by jnthn** [comment]
No, however one can write a `<:sub sk($foo><$foo.subkey></:>` and call it  like `<&sk(.attr)>`.
