### ISSUE TITLE
Extra data appearing in rendered template

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#67]
Random data is appearing.
The problem appears when the template contains an attribute <.tail>

The following template
```
<section name="<.name>">
    <.target>
    <?.tail><.tail></?>
</section>
```
called using this code snippet
```
use v6.d;
use Cro::WebApp::Template;
my %parts;
my %params = (:target<targ>, :name<NAMED>, :contents('blah blah'));
say render-template('pod.crotmp', %params ,:%parts);
```
renders to 
```
<section name="NAMED">
    blah blah
    contents    blah blah
</section>
```
The actual (extraneous) attribute that is rendered can change depending on the template compilation, so it appears to be random.

If <.tail> is eliminated, the problem disappears.

**Comment by jnthn** [comment]
https://docs.raku.org/routine/tail
