### ISSUE TITLE
Suppressing EOL / whitespace

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#68]
Use case: I need to have one set of HMTL if data is present, another if absent.
From the documentation, the only way I can do this as follows (note the disambiguation to ensure only the Hash key is tested)
```
<div id="<.name>">
<?.<tail>><.tail></?>
<!.<tail>>No tail</!>
</div>
```
HTML is produced as expected BUT there is always an extra line added in, either one corresponding to the `<!....>` stanza not generating a string, or the `<?....` not generating a string.

HTML renderers remove whitespace, so it does not have an impact on users, but I find it difficult when developing and debugging HTML if there is excessive whitespace. 

Is there a way to suppress whitespace?

Is there a better way in Crotmp to get alternate rendering depending on a boolean test?

**Comment by jnthn** [comment]
> Is there a way to suppress whitespace?

Yes, any line that only contains a conditional or iteration related tag will not introduce whitespace. Thus if you instead write:

```
<div id="<.name>">
<?.<tail>>
<.tail>
</?>
<!.<tail>>
No tail
</!>
</div>
```

Then you'll not get the blank lines.

> Is there a better way in Crotmp to get alternate rendering depending on a boolean test?

Not implemented yet, but the plan is that a `<!>...</!>` that immediately follows a positive conditional tag will do that. So it would be:

```
<div id="<.name>">
<?.<tail>>
<.tail>
</?>
<!>
No tail
</!>
</div>
```

**Comment by jnthn** [comment]
Closing in favor of #69.
