### ISSUE TITLE
Accessing other templates with same data

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#70]
Crotmp allows for subs and macros to be extracted into other templates.

This requires an explicit `<:use >` and then a call to the `<:sub ` defined therein.

I want to define the `<head>` part of an HTML page using other templates that may be compiled separately. 

Suppose for example `jquery.crotmp` is a template, and it will produce HTML. Eg.,
```
<script> blah blah </script>
```
In reality, the `jquery.crotmp` will itself need to be generated by the managing software depending on which jquery plugins are defined for that webpage. It makes sense to keep this separate from the rest of the `<head ...` template which will not change in structure from web page to webpage.

This seems to be a different type of call to the parts template that are called on multiple pages. In that a part is defined statically, but uses different data.

I would like to be able to define `headblock.crotmp` so that it accesses the compiled `jquery.crotmp`.

It seems from the documentation that I would need to write `jquery.crotmp` as 
```
<:sub jquery><script> blah blah</script></:>
```
Then in `headblock.crotmp` write
```
<:use jquery.crotmp>
<head>
    <&jquery>
etc etc
</head>
```
But in fact, I need jquery-init jquery-top jquery-bottom css , each of which need separate use and call stanzas.

It seems that the `parts` functionality does not change this much. 

Would it instead be possible to have `<:require 'jquery.crotmp'>` at the place the `<&query>` is positioned?
The current topic object would be provided to the __required__ template.

**Comment by jnthn** [comment]
> But in fact, I need jquery-init jquery-top jquery-bottom css , each of which need separate use and call stanzas.

Why would you do it that way? Write one `jquery.crotmp` that has each of the subs, and then it's use `use` and the 4 applications.

**Comment by jnthn** [comment]
Assuming there's some kind of plugin registry, I'd probably use template parts and write a part handler that obtains all the required bits for each plugin. And not as pre-formed script/style tags, but as data, and have the part handler render those.
