### ISSUE TITLE
How to test response from sub?

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro-webapp#72]
Given a sub defined elsewhere as something like
`<:sub css> ... </:>`
in another template 'css',  
how do I test its return? I have tried
```
<:use 'css'>
start of template
<?&css><&css></?><!&css>default stuff</!>
```
This does not work because `<?` can only be followed by  `.` or a variable.
I have also tried
``` 
... start of template
<?{&css eq ''}><&css><?{&css ne ''}>default stuff</?>
```
This also did not work.

It would be useful to be able to allocate some valid crotmp string, such as the return value of a sub, or perhaps a topic reference used more than once, to a variable. 
Perhaps `<:let $variable><&sub></:>`
Then it would be easy to have `<?$variable><$variable></?>`

**Comment by jnthn** [comment]
> how do I test its return?

There's not a way to do that. Consider passing the default value into the `sub` and have it make the decision instead, or some other factoring in terms of what the template language already provides.

> It would be useful to be able to allocate some valid crotmp string, such as the return value of a sub, or perhaps a topic reference used more than once, to a variable.

Such a construct will run a risk of double-encoding bugs: the `sub` returns already HTML-encoded material, but interpolations of variables also encodes.
