### ISSUE TITLE
Missing routine route-resource-resolver

### ISSUE THREAD

**Issue by Xliff** [croservices/cro-webapp#80]
The latest version of Cro::Webapp has the following block in Cro::Webapp::Template:

```
multi render-template(Str $template, $initial-topic, :%parts --> Str) is export {
    # Gather the route-specific locations and turn them into location descriptors
    # for the resolver to use.
    my @route-locations := try { router-plugin-get-configs($template-location-plugin) } // ();
    my Cro::WebApp::Template::Location @locations = @route-locations.map: {
        when TemplateResourcesLocation {
            my &resource-resolver = route-resource-resolver(error-sub => 'render-template');
            Cro::WebApp::Template::Location::Resource.new(:prefix(.prefix), :&resource-resolver)
```
Unfortunately the routine `route-resource-resolver` that is referenced above, does not exist.

**Comment by Altai-man** [comment]
@jnthn any ideas?

**Comment by jnthn** [comment]
It's [implemented here in `Cro::HTTP`](https://github.com/croservices/cro-http/blob/3cb30b32f0fda7afa7d8c91da102a48fb3234dee/lib/Cro/HTTP/Router.pm6#L1445). The code in question here in `Cro::WebApp` has never yet appeared in a release, but is just in the `master` branch; it needs `master` of `Cro::HTTP` too (we always sync the releases of these).
